---
- hosts: all
  become: true

  pre_tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - common
    - vagrant_setup
    - docker
    - devops_tools

  tasks:
    - name: Install Gnome Core
      ansible.builtin.apt:
        name: gnome-core
        state: present
